# -*- coding: utf-8 -*-
"""Nepal news scrap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y38Yj_S7kd2GwNGjZQEMgwFkBCn25YzH
"""

!pip install setuptools==58

!pip install feedparser

!pip install pygooglenews

!pip install GoogleNews

from GoogleNews import GoogleNews

import pandas as pd

gNews = GoogleNews(period = '1d')
gNews.search("Nepal")
result = gNews.result()
data = pd.DataFrame.from_dict(result)
data = data.drop(columns=["img"])
data.head()

for res in result:
  print("Title:", res["title"])
  print("Details:", res["link"])

